 const music = {
  retro: [
    {
      title: 'Безумный Мир',
      band: 'Мираж',
      cover: 'assets/img/retro-cover-0.png',
      url: './assets/audio/retro/mirazh-bezumniy-mir.mp3',
      duration: '03:40',
    },
    {
      title: 'Su Di Noi',
      band: 'Pupo',
      cover: 'assets/img/retro-cover-1.jpeg',
      url: 'assets/audio/retro/pupo-sudinoi.mp3',
      duration: '03:20',
    },
    {
      title: 'Storie Di Tutti I Giorni',
      band: 'Riccardo Fogli',
      cover: 'assets/img/retro-cover-2.jpg',
      url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
      duration: '04:02',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/retro-cover-3.jpeg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
  ],

  road: [
    {
      title: 'Where Is My Mind',
      band: 'Pixies',
      cover: 'assets/img/road-cover-0.jpeg',
      url: 'assets/audio/road/pixies-were-is-my-mind.mp3',
      duration: '03:42',
    },
    {
      title: 'Stressed Out',
      band: 'Twenty One Pilots',
      cover: 'assets/img/road-cover-1.png',
      url: 'assets/audio/road/twenty-one-pilots-stressed-out.mp3',
      duration: '03:22',
    },
    // {
    //   title: 'Storie Di Tutti I Giorni',
    //   band: 'Riccardo Fogli',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
    //   duration: '04:02',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
  ],

  punk: [
    {
      title: 'Echo and The Bunnymen',
      band: 'Nocturnal Me',
      cover: 'assets/img/punk-cover-0.jpeg',
      url: 'assets/audio/postpunk/echo-and-the-bunnymen-nocturnal-me.mp3',
      duration: '04:58',
    },
    {
      title: 'The Killing Jar',
      band: 'Siouxsie & The Banshees',
      cover: 'assets/img/punk-cover-1.jpeg',
      url: 'assets/audio/postpunk/siouxsie-and-the-banshees-the-killing-jar.mp3',
      duration: '04:05',
    },
    // {
    //   title: 'Storie Di Tutti I Giorni',
    //   band: 'Riccardo Fogli',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
    //   duration: '04:02',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
  ],

  electro: [
    {
      title: 'Wrong',
      band: 'Depeche Mode',
      cover: 'assets/img/electro-cover-1.jpeg',
      url: 'assets/audio/electro/depeche-mode-wrong.mp3',
      duration: '05:21',
    },
    {
      title: 'Wszystko Czego Dziś Chcę',
      band: 'Brodka',
      cover: 'assets/img/electro-cover-0.jpeg',
      url: 'assets/audio/electro/brodka-wszystko.mp3',
      duration: '05:59',
    },
    // {
    //   title: 'Storie Di Tutti I Giorni',
    //   band: 'Riccardo Fogli',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
    //   duration: '04:02',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
  ],

  love: [
    {
      title: 'Je t’aime Moi Non Plus',
      band: 'Jane Birkin & Serge Gainsbourg',
      cover: 'assets/img/love-cover-0.jpg',
      url: 'assets/audio/love/serge-gainsbourg-jane-birkin-je-t-aime-moi-non-plus.mp3',
      duration: '04:26',
    },
    {
      title: 'Кто-то',
      band: 'Fleur',
      cover: 'assets/img/love-cover-2.jpeg',
      url: 'assets/audio/love/fleur-kto-to.mp3',
      duration: '04:33',
    },
    // {
    //   title: 'Les Fees Carabosse',
    //   band: 'Catherine Ribeiro & 2Bis',
    //   cover: 'assets/img/love-cover-1.png',
    //   url: 'assets/audio/love/catherine-ribeiro-les-fees-carabosse.mp3',
    //   duration: '05:12',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
  ],

  beauty: [
    {
      title: 'Чувствую',
      band: 'Вера Сухомлин',
      cover: 'assets/img/beauty-cover-0.png',
      url: 'assets/audio/beauty/vera-suhomlin-chuvstvuyu.mp3',
      duration: '05:15',
    },
    {
      title: 'The Sound of Silence',
      band: 'Simon Garfunkel',
      cover: 'assets/img/beauty-cover-1.jpeg',
      url: 'assets/audio/beauty/simon-garfunkel-the-sound-of-silence.mp3',
      duration: '03:05',
    },
    // {
    //   title: 'Storie Di Tutti I Giorni',
    //   band: 'Riccardo Fogli',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
    //   duration: '04:02',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
    // {
    //   title: 'Asphalte',
    //   band: 'Alix',
    //   cover: 'assets/img/cover.jpg',
    //   url: 'assets/audio/retro/alix-asphalte.mp3',
    //   duration: '02:28',
    // },
  ],


}
export default music