 const music = {
  retro: [
    {
      title: 'Безумный Мир',
      band: 'Мираж',
      cover: 'assets/img/cover.jpg',
      url: './assets/audio/test-song-1.mp3',
      duration: '03:40',
    },
    {
      title: 'Su Di Noi',
      band: 'Pupo',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/test-song-2.mp3',
      duration: '03:20',
    },
    {
      title: 'Storie Di Tutti I Giorni',
      band: 'Riccardo Fogli',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
      duration: '04:02',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
  ],

  road: [
    {
      title: 'Where Is My Mind',
      band: 'Pixies',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/road/pixies-were-is-my-mind.mp3',
      duration: '03:40',
    },
    {
      title: 'Su Di Noi',
      band: 'Pupo',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/pupo-sudinoi.mp3',
      duration: '03:20',
    },
    {
      title: 'Storie Di Tutti I Giorni',
      band: 'Riccardo Fogli',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
      duration: '04:02',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
  ],

  punk: [
    {
      title: 'Echo and The Bunnymen',
      band: 'Nocturnal Me',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/postpunk/echo-and-the-bunnymen-nocturnal-me.mp3',
      duration: '03:40',
    },
    {
      title: 'Su Di Noi',
      band: 'Pupo',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/pupo-sudinoi.mp3',
      duration: '03:20',
    },
    {
      title: 'Storie Di Tutti I Giorni',
      band: 'Riccardo Fogli',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
      duration: '04:02',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
  ],

  electro: [
    {
      title: 'Wszystko Czego Dziś Chcę',
      band: 'Brodka',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/electro/brodka-wszystko.mp3',
      duration: '03:40',
    },
    {
      title: 'Wrong',
      band: 'Depeche Mode',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/pupo-sudinoi.mp3',
      duration: '03:20',
    },
    {
      title: 'Storie Di Tutti I Giorni',
      band: 'Riccardo Fogli',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
      duration: '04:02',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
  ],

  classic: [
    {
      title: 'Classic',
      band: 'Мираж',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/classic/simon-garfunkel-the-sound-of-silence.mp3',
      duration: '03:40',
    },
    {
      title: 'Su Di Noi',
      band: 'Pupo',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/pupo-sudinoi.mp3',
      duration: '03:20',
    },
    {
      title: 'Storie Di Tutti I Giorni',
      band: 'Riccardo Fogli',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
      duration: '04:02',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
  ],

  beauty: [
    {
      title: 'Чувствую',
      band: 'Вера Сухомлин',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/beauty/vera-suhomlin-chuvstvuyu.mp3',
      duration: '03:40',
    },
    {
      title: 'Su Di Noi',
      band: 'Pupo',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/pupo-sudinoi.mp3',
      duration: '03:20',
    },
    {
      title: 'Storie Di Tutti I Giorni',
      band: 'Riccardo Fogli',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/riccardo-fogli-storie-di-tutti-i-giorni.mp3',
      duration: '04:02',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
    {
      title: 'Asphalte',
      band: 'Alix',
      cover: 'assets/img/cover.jpg',
      url: 'assets/audio/retro/alix-asphalte.mp3',
      duration: '02:28',
    },
  ],


}
export default music